version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: ilgiznigma/freelancing-platform-project_backend
    env_file: .env
    depends_on: 
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
#      - static:/app/static/
#      - media:/app/media
  
  frontend:
    image: ilgiznigma/freelancing-platform-project_frontend
    volumes:
      - ../frontend/:/app/result_build/
#    env_file: .env
#    command: cp -r /app/build/. /static/
#    volumes:
#      - static:/static
  
  gateway:
    image: ilgiznigma/freelancing-platform-project_gateway
    env_file: .env
    ports:
      - 80:80
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/